# fly.toml app configuration file generated for api-wordlettuce on 2025-02-19T00:11:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-wordlettuce'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "libsql_data"
  destination = "/app/data" 

[env]
  AUTH_HOST="https://auth.lettucebowler.net"
  TURSO_CONNECTION_URL="libsql://wordlettuce-lettucebowler.turso.io"